### ISSUE TITLE
Bugs in Tangent Plugin

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1080]
Eugene Larin writes:

> Hi Chris,
> 
> Here is my initial list of thing to be fixed.
> The Temperature knob resets slider value to 2500, not 5000.
> The Mix knob resets slider value to 0.
> When adjusting multiple controls (knobs and wheels), first adjustment takes priority. Effectively it's not possibly not make multiple adjustment simultaneously.
> Fast knob adjustment results in delayed UI response.
> Very noticeable delay when adjusting the Temperature knob.
> Very noticeable delay when adjusting the Tint knob.
> MacBook Pro (Retina, 15-inch, Mid 2015), 2.2 GHz Intel Core i7, 16 GB 1600 MHz DDR3, Intel Iris Pro 1536 MB.
> 
> Tangent Element Tk, Tangent Element Kb, Tangent Element Bt.
> 
> Probably most of the usability issues caused by Apple not providing a proper API, so no pressure on you. You've already done a great job.
> 
> I can test the thing on a wide variety of Apple hardware.
> 
> Thanks.

**To-do list:**

- [x] The Temperature knob resets slider value to 2500, not 5000.
- [x] The Mix knob resets slider value to 0.
- [x] When adjusting multiple controls (knobs and wheels), first adjustment takes priority. Effectively it's not possibly not make multiple adjustment simultaneously.
- [x] Fast knob adjustment results in delayed UI response.
- [ ] Very noticeable delay when adjusting the Temperature knob.
- [ ] Very noticeable delay when adjusting the Tint knob.

**Comment by latenitefilms** [comment]
Andy writes...

> We loaded up Command Post yesterday and had a play. It’s looking great J
> The only issues that we’ve found are the smoothness & lag, especially of the color wheel controls.
>  
> Multiple controls
> When moving the trackerballs in the X axis only they behave OK however when moving vertically (together with some small unintentional horizontal movement) they are very steppy. It’s as if the horizontal movement takes priority and the vertical movement is only processed occasionally. I can achieve the same effect by moving Temperature and Hue at the same time – Temp takes priority and Hue only responds if you stop moving Temp. I’m pretty sure that I know what’s going on here:
>  
> If multiple controls are moved at the same time on the panel (e.g. a single trackerball which is effectively 2 encoders) then the message which you receive from the Hub will messages encapsulate a number of commands. Each message starts with a 32 bit integer value which indicates the number of bytes that will follow to complete the message. Commands then follow one by one until the message is complete.
>  
> Format:            <numBytes>, <command1>, <command2>, …
>  
> I strongly suspect that you’re reading the first command and then discarding any subsequent commands within the message.
> I’ve been able to confirm this by swapping the Temp and Hue parameters over on the panel. Now Hue takes priority over Temp i.e. if more than one command is initiated within the poll period (40mS) then the command caused by the lowest ID encoder is acted upon while others are discarded.
>  
> Lag / Overrun
> I’ve noticed that some parameters behave differently to others e.g. Temperature and Tint are rock-solid and respond perfectly however Hue has quite a lag and continues changing after the control stops moving.
> I’m assuming that this is because we’re running on an ancient MacBook and the parameter change commands are being queued up because they can’t be processed in real-time.
>  
> There’s a few other things that I’d like to chat to you about but nothing major.
